tls:
    keystore:
        type: "pkcs12"
        path: "certs/super-tickets-papi.p12"
        alias: "mule-server"
        keyPassword: "superSecretPassword" 
        password: "superSecretPassword"     
        
api:
  id: "19409007"